name = "live"
type = "webpack"
account_id = "fd93b137ef2b433cd1b8383bcc095c74"
workers_dev = true
route = "noctis-alba.com/*"
zone_id = "fee58c1bfc6995c4c5227ee4b4ebf7ad"

[site]
bucket = "./public"
entry-point = "workers-site"